name: Release 

on:
  push:
    branches: [ main ]
    tags: ["*"]
 
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_TOKEN }} # token is on "github secrets"

      - name: Build and push container image
        run: sbt dockerBuildAndPush
